# Generated by Django 3.1.3 on 2020-11-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_position_trade_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='average',
            new_name='price',
        ),
    ]
